version: '3.7'

services:
  db:
    container_name: brasileirao_db
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brasileirao
      - POSTGRES_PORT=5432
